### ISSUE TITLE
REQUEST: New membership for <BlackBear2003>

### ISSUE THREAD

**Issue by spaceluke** [ctripcorp/apollo-community#10]
### GitHub Username

@BlackBear2003

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/apolloconfig/apollo/blob/master/GOVERNANCE.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Apollo repositories

### List of contributions to the Apollo community

- PRs reviewed/authored
  - https://github.com/apolloconfig/apollo/pull/4985
  - https://github.com/apolloconfig/apollo/pull/5008
  - https://github.com/apolloconfig/apollo/pull/5030
  - https://github.com/apolloconfig/apollo/pull/5055
  - https://github.com/apolloconfig/apollo/pull/5072
  - https://github.com/apolloconfig/apollo/pull/5149
  - https://github.com/apolloconfig/apollo/pull/5153
  - https://github.com/apolloconfig/apollo/pull/5302
- Issues responded to
  - https://github.com/apolloconfig/apollo/issues/5029
  - https://github.com/apolloconfig/apollo/issues/5051
  - https://github.com/apolloconfig/apollo/issues/4372

**Comment by nobodyiam** [comment]
+1

**Comment by Anilople** [comment]
+1

**Comment by nobodyiam** [comment]
@BlackBear2003 You have been added to the Apollo organization, please check the invitation from GitHub.
