### ISSUE TITLE
REQUEST: New membership for mghio

### ISSUE THREAD

**Issue by mghio** [ctripcorp/apollo-community#4]
### GitHub Username

@mghio

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/apolloconfig/apollo/blob/master/GOVERNANCE.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Apollo repositories

### List of contributions to the Apollo community

- PRs reviewed/authored
  - https://github.com/apolloconfig/apollo/pull/4137
  - https://github.com/apolloconfig/apollo/pull/3755
- Issues responded to
  - https://github.com/apolloconfig/apollo/issues/3874
  - https://github.com/apolloconfig/apollo/issues/2939

**Comment by nobodyiam** [comment]
+1

**Comment by lepdou** [comment]
+1

**Comment by Anilople** [comment]
+1

**Comment by nobodyiam** [comment]
@mghio You have been added to the Apollo organization, please check the invitation from GitHub.
