### ISSUE TITLE
REQUEST: New membership for hezhangjian

### ISSUE THREAD

**Issue by hezhangjian** [ctripcorp/apollo-community#5]
### GitHub Username

@hezhangjian 

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/apolloconfig/apollo/blob/master/GOVERNANCE.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more Apollo repositories

### List of contributions to the Apollo community

- PRs reviewed/authored
  - https://github.com/apolloconfig/apollo/pull/4392
  - https://github.com/apolloconfig/apollo/pull/4312
  - https://github.com/apolloconfig/apollo/pull/4202
  - https://github.com/apolloconfig/apollo/pull/4199
  - https://github.com/apolloconfig/apollo/pull/4189
  - https://github.com/apolloconfig/apollo/pull/4182
  - https://github.com/apolloconfig/apollo/pull/4193
  - https://github.com/apolloconfig/apollo/pull/4182
  - https://github.com/apolloconfig/apollo/pull/4464
- Issues responded to
  - https://github.com/apolloconfig/apollo/issues/4457

**Comment by nobodyiam** [comment]
+1

**Comment by JaredTan95** [comment]
+1 support

**Comment by nobodyiam** [comment]
@hezhangjian  You have been added to the Apollo organization, please check the invitation from GitHub.
